# Change these first
owner: lanen # Your GitHub organization or username, where this repository lives
repo: bs-site # The name of this repository

sites:
  - name: Buckydrop
    url: https://www.buckydrop.com
  - name: Superbuy
    url: https://www.superbuy.com
  - name: ctiktok.net
    url: https://www.ctiktok.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: lanen.github.io
  baseUrl: /bs-site
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 站外监控
  introTitle: "**站外监控** ask evan."
  introMessage: OK
  navbar:
    - title: Status
      href: /bs-site
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
